[alias]
readfs = ""

[build]
target = "riscv32imac-unknown-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]


[unstable]
build-std = ["alloc", "core"]